# use to setup dev environment
version: "3.9"
services:
  nsi_server:
    container_name: NSISERVER_DEV
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3031:3031
    volumes:
      - $PWD:/workspaces/nsi_survey_server
      - $PWD/../microauth:/workspaces/microauth
    env_file:
      - .devcontainer/devcontainer.env
    working_dir: /workspaces/nsi_survey_server
    tty: true
